-- Sample Data Insertion Script
-- Insert 60 records into DataRecords table

INSERT INTO DataRecords (SerialNo, Name, City) VALUES
(1, 'John Smith', 'New York'),
(2, 'Jane Doe', 'Los Angeles'),
(3, 'Michael Brown', 'Chicago'),
(4, 'Emily Davis', 'Houston'),
(5, 'David Wilson', 'Phoenix'),
(6, 'Sarah Miller', 'Philadelphia'),
(7, 'James Taylor', 'San Antonio'),
(8, 'Jessica Anderson', 'San Diego'),
(9, 'Robert Thomas', 'Dallas'),
(10, 'Amanda Jackson', 'San Jose'),
(11, 'William White', 'Austin'),
(12, 'Rachel Harris', 'Jacksonville'),
(13, 'Richard Martin', 'Fort Worth'),
(14, 'Lauren Thompson', 'Columbus'),
(15, 'Joseph Garcia', 'Charlotte'),
(16, 'Megan Martinez', 'San Francisco'),
(17, 'Charles Robinson', 'Indianapolis'),
(18, 'Ashley Clark', 'Austin'),
(19, 'Thomas Rodriguez', 'Memphis'),
(20, 'Brittany Lewis', 'Boston'),
(21, 'Christopher Lee', 'Seattle'),
(22, 'Elizabeth Walker', 'Denver'),
(23, 'Daniel Hall', 'Washington DC'),
(24, 'Margaret Allen', 'Nashville'),
(25, 'Matthew Young', 'Baltimore'),
(26, 'Patricia Hernandez', 'Louisville'),
(27, 'Mark King', 'Milwaukee'),
(28, 'Barbara Wright', 'Albuquerque'),
(29, 'Donald Lopez', 'Tucson'),
(30, 'Susan Hill', 'Fresno'),
(31, 'Steven Scott', 'Sacramento'),
(32, 'Jessica Green', 'Long Beach'),
(33, 'Paul Adams', 'Kansas City'),
(34, 'Karen Nelson', 'Mesa'),
(35, 'Andrew Carter', 'Virginia Beach'),
(36, 'Donna Roberts', 'Atlanta'),
(37, 'Joshua Phillips', 'St. Louis'),
(38, 'Michelle Campbell', 'Riverside'),
(39, 'Kenneth Parker', 'Corpus Christi'),
(40, 'Betty Evans', 'Lexington'),
(41, 'Kevin Edwards', 'Henderson'),
(42, 'Sandra Collins', 'Plano'),
(43, 'Brian Reeves', 'Stockton'),
(44, 'Kathleen Morris', 'Cincinnati'),
(45, 'Edward Rogers', 'Saint Paul'),
(46, 'Shirley Reed', 'Irvine'),
(47, 'Ronald Cook', 'Chula Vista'),
(48, 'Angela Morgan', 'Toledo'),
(49, 'Aaron Peterson', 'Chandler'),
(50, 'Brenda Cooper', 'Laredo'),
(51, 'Jose Bell', 'Durham'),
(52, 'Anna Cox', 'Lubbock'),
(53, 'Adam Howard', 'Winston-Salem'),
(54, 'Dorothy Ward', 'Garland'),
(55, 'Henry Torres', 'Glendale'),
(56, 'Samantha Peterson', 'Irving'),
(57, 'Douglas Gray', 'Chesapeake'),
(58, 'Maria Ramirez', 'Garland'),
(59, 'Peter James', 'North Las Vegas'),
(60, 'Joyce Watson', 'Scottsdale');
